const translations = {
    vi: {
  	checknoti: "Cho phép Thông báo",
	checknotiText: "để biết khi kho lưu trữ có cập nhật ứng dụng.",
        continu: "Tiếp tục",
        statusTitle: "Trạng thái",
	statusText: "Đã bật tính năng thông báo.",
	statusTextNo: "Bạn cần cho phép thông báo để tính năng này hoạt động.",
        newapps: " ứng dụng mới",
	updatedapps: " ứng dụng được cập nhật",
	removedapps: " ứng dụng bị xóa",
        hasupdate: "có cập nhật, Refresh ngay!",
	total: "Tổng",
	found: "Tìm thấy",
	nothingfound: "Không tìm thấy app nào!",
	enterapp: "Nhập tên ứng dụng...",
        addto: "Thêm vào",
	addtowhat: "Thêm TEXT vào Esign?",
	addtorecieve: "Thêm TEXT vào Esign để nhận bản cập nhật ứng dụng",
	addtorecieve2: "Thêm TEXT vào Feather để nhận bản cập nhật ứng dụng",
	whichapp: "Chọn ứng dụng quản lý",
        installviaesign: "Cài đặt qua Esign",
        downloadipa: "Tải xuống IPA",
        installapp: "Cài đặt ngay",
        copylink: "Sao chép link",
        cancel: "Hủy",
        version: "Phiên bản",
        copysuccess: "Đã sao chép link vào bộ nhớ đệm!\nDán link vào safari hoặc Esign \nTải xuống ⇒ URL ⇒ OK",
        copyfailed: "Không thể sao chép đường dẫn tệp IPA!",
        addtoesign: "Thêm vào Esign",
        addtoesignText: "Nếu bạn có Esign, thêm kho lưu trữ này vào bạn có thể tải các bản cập nhật mới nhất ngay khi có.",
        allversion: "Tất cả phiên bản",
        whatnew: "Tính năng mới",
        preview: "Xem trước",
        get: "Nhận",
        back: "Quay lại",
        done: "Đóng",
        apppermit: "Quyền ứng dụng",
        notpermit: "Thông tin về quyền không được cung cấp trong kho lưu trữ.",
        discovermore: "Khám phá thêm",
        unknown: "Không biết",
        more: "xem thêm",
        allrepo: "Tất cả kho lưu trữ",
        allapps: "Tất cả ứng dụng",
        featuredapps: "Ứng dụng nổi bật",
        allnews: "Tất cả tin tức",
        news: "Tin tức",
        contents: "NỘI DUNG",
        lastupdate: "Cập nhật",
        tablecontent: "Mục Lục",
        howtoinstall: "Cách cài đặt KhoIPA?",
        howtoinstallText: "Chọn nút Chia sẻ → Thêm vào Màn hình chính → Xong",
        today: "Hôm nay",
        yesterday: "Hôm qua",
        monthago: "tháng trước",
        monthsago: "tháng trước",
        dayago: "ngày trước",
        daysago: "ngày trước",
        weekago: "tuần trước",
        weeksago: "tuần trước",
        success: "Thành công",
        errorapp: "Không có app tương ứng.",
        error: "Lỗi",
        about: "Giới thiệu",
        featuredrepo: "Kho lưu trữ nổi bật",
        disclaimer: "Tuyên bố miễn trừ trách nhiệm",
        disclaimerText: "Mọi nội dung gốc đều thuộc quyền sở hữu của các tác giả hợp pháp.\nCác tệp IPA đã chỉnh sửa chỉ được cung cấp nhằm mục đích sử dụng cá nhân và học tập.\nTrang này không có bất kỳ mục đích thương mại nào.",
        updategame: "Trò chơi mới cập nhật",
        updateapp: "Ứng dụng mới cập nhật",
        home: "Trang chủ",
        search: "Tìm kiếm",
        source: "Nguồn",
        view: "Xem",
        entilement: "Quyền bổ sung",
        privacy: "Quyền riêng tư",
        privacyText: "có thể yêu cầu các chứng năng sau",
        entilementText: "Quyền bổ sung là những quyền bổ sung cho phép ứng dụng truy cập vào một số dịch vụ hệ thống, bao gồm cả những thông tin có thể nhạy cảm."
    },
    ru: {
	statusTitle: "Статус",
	statusText: "Функция уведомлений включена.",
	statusTextNo: "Необходимо разрешить уведомления, чтобы эта функция работала.",
	newapps: " новые приложения",
	updatedapps: " обновленные приложения",
	removedapps: " удаленные приложения",
	hasupdate: "есть обновление, обновите сейчас!",
        total: "Всего",
        found: "Найдено",
        nothingfound: "Приложения не найдены!",
        enterapp: "Введите название приложения...",
        addto: "Добавить в",
	addtowhat: "Добавить TEXT в Esign?",
	addtorecieve: "Добавь TEXT в Esign, чтобы получить обновление приложения.",
	addtorecieve2: "Добавь TEXT в Feather, чтобы получить обновление приложения.",
	whichapp: "Выберите приложение для управления",
        installviaesign: "Установить через Esign",
        downloadipa: "Скачать IPA",
        installapp: "Установить сейчас",
        copylink: "Копировать ссылку",
        cancel: "Отмена",
        version: "Версия",
        copysuccess: "Ссылка скопирована в буфер обмена!\nВставьте ссылку в Safari или Esign\nСкачать ⇒ URL ⇒ OK",
        copyfailed: "Не удалось скопировать ссылку на IPA файл!",
        addtoesign: "Добавить в Esign",
        addtoesignText: "Если у вас есть Esign, добавьте этот репозиторий, чтобы получать последние обновления сразу после их выхода.",
        allversion: "Все версии",
        whatnew: "Что нового",
        preview: "Предпросмотр",
        get: "Загрузить",
        back: "Назад",
        done: "Готово",
        apppermit: "Разрешения приложения",
        notpermit: "Информация о разрешениях не предоставлена в репозитории.",
        discovermore: "Узнать больше",
        unknown: "Неизвестно",
        more: "еще",
        allrepo: "Все репозитории",
        allapps: "Все приложения",
        featuredapps: "Рекомендуемые приложения",
        allnews: "Все новости",
        news: "Новости",
        contents: "СОДЕРЖАНИЕ",
        lastupdate: "Обновлено",
        tablecontent: "Оглавление",
        howtoinstall: "Как установить KhoIPA?",
        howtoinstallText: "Нажмите кнопку Поделиться → На экран «Домой» → Готово",
        today: "Сегодня",
        yesterday: "Вчера",
        monthago: "месяц назад",
        monthsago: "месяцев назад",
        dayago: "день назад",
        daysago: "дней назад",
        weekago: "неделю назад",
        weeksago: "недель назад",
        success: "Успешно",
        errorapp: "Соответствующее приложение не найдено.",
        error: "Ошибка",
        about: "О нас",
        featuredrepo: "Рекомендуемые репозитории",
        disclaimer: "Отказ от ответственности",
        disclaimerText: "Весь оригинальный контент принадлежит законным правообладателям.\nМодифицированные IPA-файлы предоставляются исключительно для личного использования и ознакомления.\nЭтот ресурс не преследует никаких коммерческих целей.",
        updategame: "Недавно обновленные игры",
        updateapp: "Недавно обновленные приложения",
        home: "Главная",
        search: "Поиск",
        source: "Источник",
        view: "Просмотр",
        entilement: "Дополнительные права",
        privacy: "Конфиденциальность",
        privacyText: "может запрашивать следующие функции",
        entilementText: "Дополнительные права позволяют приложению получать доступ к определенным системным службам, включая конфиденциальную информацию."
    },
    ja: {
	statusTitle: "ステータス",
	statusText: "通知機能が有効になっています。",
	statusTextNo: "この機能を利用するには通知を許可する必要があります。",
	newapps: " 新しいアプリ",
	updatedapps: " 更新されたアプリ",
	removedapps: " 削除されたアプリ",
	hasupdate: "更新があります。今すぐリフレッシュ！",
        total: "合計",
        found: "見つかりました",
        nothingfound: "アプリが見つかりません！",
        enterapp: "アプリ名を入力...",
        addto: "に追加",
	addtowhat: "EsignにTEXTを追加しますか？",
	addtorecieve: "EsignにTEXTを追加して、アプリの更新を受け取ります。",
	addtorecieve2: "FeatherにTEXTを追加して、アプリの更新を受け取ります。",
	whichapp: "管理アプリを選択してください",
        installviaesign: "Esignでインストール",
        downloadipa: "IPAをダウンロード",
        installapp: "今すぐインストール",
        copylink: "リンクをコピー",
        cancel: "キャンセル",
        version: "バージョン",
        copysuccess: "リンクをクリップボードにコピーしました！\nSafariまたはEsignに貼り付けてください。\nダウンロード ⇒ URL ⇒ OK",
        copyfailed: "IPAファイルのリンクをコピーできませんでした。",
        addtoesign: "Esignに追加",
        addtoesignText: "Esignをお持ちの場合、このリポジトリを追加すると最新のアップデートをすぐに取得できます。",
        allversion: "すべてのバージョン",
        whatnew: "新機能",
        preview: "プレビュー",
        get: "入手",
        back: "戻る",
        done: "完了",
        apppermit: "アプリの権限",
        notpermit: "リポジトリ内に権限情報がありません。",
        discovermore: "もっと見る",
        unknown: "不明",
        more: "さらに表示",
        allrepo: "すべてのリポジトリ",
        allapps: "すべてのアプリ",
        featuredapps: "おすすめのアプリ",
        allnews: "すべてのニュース",
        news: "ニュース",
        contents: "コンテンツ",
        lastupdate: "最終更新",
        tablecontent: "目次",
        howtoinstall: "KhoIPAのインストール方法",
        howtoinstallText: "共有ボタンをタップ → ホーム画面に追加 → 完了",
        today: "今日",
        yesterday: "昨日",
        monthago: "ヶ月前",
        monthsago: "ヶ月前",
        dayago: "日前",
        daysago: "日前",
        weekago: "週間前",
        weeksago: "週間前",
        success: "成功",
        errorapp: "該当するアプリがありません。",
        error: "エラー",
        about: "紹介",
        featuredrepo: "注目のリポジトリ",
        disclaimer: "免責事項",
        disclaimerText: "すべてのオリジナルコンテンツは正当な著作者に帰属します。\n修正済みIPAファイルは個人利用および学習目的のみで提供されています。\n本サイトは営利目的ではありません。",
        updategame: "更新されたゲーム",
        updateapp: "更新されたアプリ",
        home: "ホーム",
        search: "検索",
        source: "ソース",
        view: "表示",
        entilement: "追加の権限",
        privacy: "プライバシー",
        privacyText: "以下の機能を要求する場合があります",
        entilementText: "追加の権限とは、アプリが機密情報を含む特定のシステムサービスにアクセスすることを許可するものです。"
    },
    en: {
  	checknoti: "Enable Notification",
	checknotiText: "to recive newest update information.",
        continu: "Continue",
	statusTitle: "Status",
	statusText: "Notification feature is enabled.",
	statusTextNo: "You need to allow notifications for this feature to work.",
        newapps: " new apps",
	updatedapps: " updated apps",
	removedapps: " removed apps",
	hasupdate: "has update, Refresh now!",
	total: "Total",
	found: "Found",
	nothingfound: "Nothing found!",
	enterapp: "Enter app name...",
        addto: "Add to",
	addtowhat: "Add TEXT to Esign?",
	addtorecieve: "Add TEXT to Esign to receive app updates",
	addtorecieve2: "Add TEXT to Feather to receive app updates",
	whichapp: "Choose a management app",
        installviaesign: "Install via Esign",
        installapp: "Install App",
        downloadipa: "Download IPA",
        copylink: "Copy Link IPA",
        cancel: "Cancel",
        version: "Version",
        copysuccess: "Copied to clipboard! \nPaste the link into Safari or Esign \nDownload ⇒ URL ⇒ OK",
        copyfailed: "Unable to copy the IPA download link!",
        addtoesign: "Add to Esign",
        addtoesignText: "If you have Esign, add this source so you'll receive notifications when app updates are available.",
        allversion: "All Versions",
        whatnew: "What's New",
        preview: "Preview",
        get: "GET",
        done: "Done",
        back: "Back",
        apppermit: "App Permissions",
        notpermit: "The developer has not specified any permissions for this app.",
        discovermore: "Discover More On",
        unknown: "Unknown",
        more: "more",
        allrepo: "All Repositories",
        allapps: "All Apps",
        featuredapps: "Featured Apps",
        allnews: "All News",
        news: "News",
        contents: "CONTENTS",
        lastupdate: "Last updated",
        tablecontent: "Table Content",
        howtoinstall: "How to Install KhoIPA?",
        howtoinstallText: "Select Share Button -> Add To Home Screen  -> Done",
        today: "Today",
        yesterday: "Yesterday",
        monthago: "month ago",
        monthsago: "months ago",
        dayago: "day ago",
        daysago: "days ago",
        weekago: "week ago",
        weeksago: "weeks ago",
        success: "Success",
        error: "Error",
        errorapp: "No corresponding app found.",
        view: "View",
        entilement: "Entitlements",
        privacy: "Privacy",
        privacyText: "may request to access the following",
        entilementText: "Entitlements are additional permissions that grant access to certain system services, including potentially sensitive information."
    }
};
window.isPWA = window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;
window.langCode = getAppLanguage();
window.langText = translations[langCode] || translations['en'];
window.isReload = false;
window.oldTargetPage = "page-home";

document.querySelector('meta[property="og:url"]')?.setAttribute("content", window.location.origin);
document.documentElement.lang = langCode;
document.querySelectorAll('span[data-text]').forEach(
    span => span.textContent = langText[span.dataset.text] ?? span.textContent);

export const urlSearchParams = new URLSearchParams(window.location.search);
export const sourceURL = base64Convert(
        decodeURIComponent(urlSearchParams.get('source')?.replaceAll("+", "%2B") ?? 'aHR0cHMlM0ElMkYlMkZyYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tJTJGZHJwaGUlMkZLaG9JUEElMkZtYWluJTJGdXBsb2FkJTJGcmVwby5mYXZvcml0ZS5qc29u'),
        'decode');

export const bundleID = urlSearchParams.get('bundleID') ?? '';
export const noteURL = urlSearchParams.get('note') ?? '';
export const dirNoteURL = "https://drphe.github.io/KhoIPA/view/?note=";

export const urlRegex = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;()]*[-A-Z0-9+&@#\/%=~_|)])/ig;

export function base64Convert(text, mode = 'encode') {
    if (mode === 'encode') {
        return btoa(encodeURIComponent(text));
    } else if (mode === 'decode') {
        try {
            const urlDecoded = decodeURIComponent(text);
            return decodeURIComponent(atob(urlDecoded));
        } catch (e) {
            console.error("Base64 decode failed:", e);
            return null;
        }
    } else {
        throw new Error("Accept only 'encode' or 'decode'.");
    }
}

export function getAppLanguage() {
    const browserLang = navigator.language || navigator.userLanguage;
    const langCode = browserLang.toLowerCase().split('-')[0];
    return langCode;
}
